### ISSUE TITLE
Dependencies from pubspec.yaml are not listed

### ISSUE THREAD

**Issue by seihan** [shamblett/sbom#3]
I can't generate a sbom.spdx file which includes all dependencies from the pubspec.yaml as mentioned.

> The SBOM is generated from the Dart files contained in the package plus the pubspec.yaml, no other files included in the package are currently considered.

Can you please extend the example for this case? My goal is a list with all dependencies inside my app / package.

**Comment by shamblett** [comment]
I need more information , what do you mean by 'all dependencies from the pubspec.yaml'? Dependencies in the pubspec are individual packages that should have their own SBOM's or do you mean you just want them listed in the SBOM as a relationship or something?

**Comment by seihan** [comment]
Yes I mean that they are listed like all internal files but referenced to the package source. If this is out of the scope of this package, please let my know. Anyway, thank you for working on this package. My use cases for this list are supply-chain transparency and security, to report which software components are part of the app and are there security issues. This for I would recommend to include all dart packages and flutter plugins into the scanner.

**Comment by shamblett** [comment]
OK, but why would you need to list them like all internal files? These files don't belong to this package, they belong to other packages so they should be listed in the SBOM for that package. The best this package can do is generate an external dependency reference maybe indicating where this information could be found.

**Comment by seihan** [comment]
I misunderstood the purpose of the package. Thank you for the clarification.
